#pragma once

#ifndef SOME_CONST_H
#define SOME_CONST_H


#include "Library.h"
#define NUMBER_ITEM 200
#define NUMBER_BULLET 200
#define NUMBER_ENNEMIES 50
#define ENNEMIES_C_SPEED 5
#define ENNEMIES_D_SPEED 5
#define SPEED_BULLET_PLAYER 6
#define DAMAGE_BULLET_PLAYER 5

#define SPEED_BUllET_LEVEL
#define SPEED_BUllET_TRIANGLE
#define SPEED_BUllET_STAR 


#define SPEED_BULLET_ENNEMIES_A 5
#define SPEED_BULLET_ENNEMIES_B 3
#define SPEED_BULLET_ENNEMIES_C 3
#define SPEED_BULLET_ENNEMIES_D 3
#define SPEED_BULLET_ENNEMIES_E 3
#define DAMAGE_BULLET_ENNEMIES 5
#define DELAY_BULLET_ENNEMIES_A 400
#define DELAY_BULLET_ENNEMIES_B 600
#define DELAY_BULLET_ENNEMIES_C 600
#define DELAY_BULLET_ENNEMIES_D 700
#define DELAY_BULLET_ENNEMIES_E 500

#define HEALTH_ENNEMIES_A 20
#define HEALTH_ENNEMIES_B 30
#define HEALTH_ENNEMIES_C 40
#define HEALTH_ENNEMIES_D 50
#define HEALTH_ENNEMIES_E 50

#define PI 3.141592
#define NUMBER_MAX_WIDTH 46
#define NUMBER_MAX_HEIGHT 64
#define EDGE_LENGTH_BLOCK 20
#define DELAY_BULLET 120


const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 1000;

enum screenstatus {
	PAUSE,
	HOME,
	FIGHT,
	GAMEOVER,
	WARNING,
	OPTION,
	CREDIT,
};
enum buff {
	NONE,
	SHIELD,
	SUPPORT,
	SPEED_BULLET,
	BULLET_X5,
	BULLET_X7,
};
enum Map {
	WAVE_1,
	WAVE_2,
	WAVE_3,
	WAVE_4,
};
enum ennemies {
	ENNEMIES_1,
	ENNEMIES_2,
	ENNEMIES_3,
	ENNEMIES_4,
};
#endif
